### ISSUE TITLE
Integration with Better Bib(La)TeX (BBT) 

### ISSUE THREAD

**Issue by gracile-fr** [ZotPlus/zotero-report-customizer#11]
It is written on the BBT webbage that you can "find duplicate keys through integration with Report Customizer". How does this work?
I've three items which have the same author, the same year, and almost the same title (i.e. the first words of their titles are identical). Their BBT (pinned) keys are: "author_title_1983", "author_title_1983-1" and "author_title_1983-1", i.e. two have the same key.

But they're nothing which indicates any conflicts in the zotero report I generated from these three items. Am I missing something?

Zotero Report Customizer 0.2.13 ; Zotero BBT 1.1.1 ; ZotPlus Report ID: XW3NTJQH

Thanks for your great work!

**Comment by retorquere** [comment]
That integration got broken in the 1.X releases of BBT; it should now be back in RC 0.2.16. duplicate keys will have the text `duplicate` behind the key.

**Comment by gracile-fr** [comment]
Thank you very much! Is it normal / frequent to have duplicate keys? How can I avoid that, or at least be informed? My library have 1900 top items, I can't generate such a big report.

**Comment by retorquere** [comment]
I have a 4.7K library, took about 6 seconds to generate a report on that. How frequent it is depends on your settings and your activity. There are two things that will create duplicates:

* You manually set key values to duplicates by editing the extra field directly, or
* You generate keys, but have key conflict policy set to "keep" in the settings.

**Comment by retorquere** [comment]
There is no feedback on duplicates being generated by either of these two methods other than the report generated by report customizer.

**Comment by gracile-fr** [comment]
OK. If I select all my items and generate a report I get this error in the Report window: "TypeError: Zotero.BetterBibTeX.keymanager.get(...) is undefined". ID : JGQ45RUJ

I didn't manually set keys for these items afair (I might be wrong obviously) ; my key conflict policy is "keep".

**Comment by gracile-fr** [comment]
Found the "bug": I've some attachments without parent item.

**Comment by retorquere** [comment]
That should not cause errors.

**Comment by retorquere** [comment]
Can you file a new issue for that?

**Comment by gracile-fr** [comment]
ID: 8XTPD986 (start standalone, select a pdf without parent, generate a report)

**Comment by retorquere** [comment]
I would appreciate a new issue to track this. Right now I'm just tracking it by email, which is bound to get lost

**Comment by gracile-fr** [comment]
ok

**Comment by gracile-fr** [comment]
ok, sorry. I understood "new ID" for "new issue" in your last comment. Sorry about that. I'm creating a new github issue.
