### ISSUE TITLE
TypeError: Zotero.BetterBibTeX.keymanager.get(...) is undefined

### ISSUE THREAD

**Issue by gracile-fr** [ZotPlus/zotero-report-customizer#12]
If I select all my items and generate a report, I get this error in the Report window: "TypeError: Zotero.BetterBibTeX.keymanager.get(...) is undefined". ID : JGQ45RUJ

The bug seems to be that I've some attachments without parent items. If I deselect them, I don't get this error. (That would be great to take that into account at some point, but I can create a specific saved search in the meantime, no hurry.)

Another Report ID:  8XTPD986 (start standalone, select one pdf without parent, generate a report)

**Comment by retorquere** [comment]
Easy to fix, but I'm at the zoo with my daughter. Priorities :)

**Comment by gracile-fr** [comment]
No pb, I hope you're both enjoying it :-)
(I'm going to file some issues, I hope that's ok for you. I really appreciate your work)

**Comment by retorquere** [comment]
Well at some point she was way ahead of me in the enjoyment department -- 7 year olds have a secret stash of limitless energy it seems.

Issue reports are always welcome.

**Comment by retorquere** [comment]
http://tempsend.com/823ACA6A3E should fix it -- could you test?

**Comment by gracile-fr** [comment]
Works perfectly now. Thanks! (just to be sure: attachments without parent item have no key, right?)

**Comment by retorquere** [comment]
That is correct.
