### ISSUE TITLE
Tabular reports

### ISSUE THREAD

**Issue by earcanal** [ZotPlus/zotero-report-customizer#15]
I have a specific use case where I would like a tabular report GROUPed BY tags attached to notes.  I currently have a hack for this using structured text in notes, CSV export and a perl script!  A more generic (SQL?) query interface with tabular output might be the best implementation approach.

**Comment by retorquere** [comment]
SQL group by only works if you somehow summarise the non-grouped-by fields; how do you work around that? And how do you group by tag when an item has multiple tags, do you have it show up in more than one place?

**Comment by earcanal** [comment]
I can probably address my use case myself having discovered that Zotero data is stored in sqlite!

**Comment by retorquere** [comment]
It is indeed. Keep in mind the DB might be locked during use by Zotero.
