### ISSUE TITLE
RFE: sign the xpi

### ISSUE THREAD

**Issue by chrislong** [ZotPlus/zotero-report-customizer#17]
The plugin is unsigned, so Firefox complains that it "could not be installed because it could not be verified." It would be nice to not have to disable signing checking to install this.

**Comment by retorquere** [comment]
Can you try whether .19 does the job?

**Comment by chrislong** [comment]
Yup, .19 works. It was hard to find, though, because it's not linked from the github page.

Thanks for the quick reply.

**Comment by retorquere** [comment]
Didn't it just update itself?

**Comment by chrislong** [comment]
I don't think it occurred to me to try that since it seemed like an older version than what I had.
