### ISSUE TITLE
 Report Customizer - Blank output

### ISSUE THREAD

**Issue by gracile-fr** [ZotPlus/zotero-report-customizer#9]
FYI https://forums.zotero.org/discussion/47309/report-customizer-blank-output/#Item_0

**Comment by AllThatIsTheCase** [comment]
Can you
1. go into Preferences->Advanced->Enable and check the box saying "Enable after restart"
2. restart firefox (make sure it actually restarts -- no windows or dialog boxes open
3. generate a report
4. Go into Preferences->Advanced and click "View"
5. Paste the output in https://gist.github.com/ and post the resulting URL here

**Comment by anonymus507** [comment]
https://gist.github.com/anonymous/3be7bc8618f04573de5d
